[package]
name = "inzinerinis_projektas"
version = "0.1.0"
edition = "2024"

[dependencies]
rayon = "1.11.0"
clap = { version = "4.5", features = ["derive"] }

[dev-dependencies]
criterion = { version = "0.7", features = ["html_reports"] }

[[bench]]
name = "benchmark"
harness = false
